name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5

      - name: Install Terraform Provider
        run: |
          mkdir -p ~/.terraform.d/plugins
          curl -LO "https://releases.hashicorp.com/terraform-provider-aws/5.6.2/terraform-provider-aws_5.6.2_linux_amd64.zip"
          unzip terraform-provider-aws_5.6.2_linux_amd64.zip -d ~/.terraform.d/plugins

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Apply Terraform
        run: terraform apply -auto-approve
